name: Create the Kubernetes manifest
description: This action will create the Kubernetes manifest by using cdk8s. By doing this we do not have to create manifests manually for our applications.
inputs:
  app_name:
    description: The application name
    required: true
    default: ''
  service_type:
    description: Service type selector. I.e. webservice.
    required: true
    default: ''
  namespace:
    description: The Kubernetes namespace
    required: true
    default: development
  instance:
    description: The instance running. Example here would be i.e. previews, development, api. It is used to select which node group we want to run the pod.
    required: true
  docker_image:
    description: The full docker image with tag. <url>/<repo>:<tag>
    required: true
    default: ''
  nodegroup:
    description: The node group it should be deployed to. Based on the Node Group instance tag. I.e. ng-development, ng-staging
    required: false
  port:
    description: The exposed port number used by the application
    required: false
    default: ''
  container_port:
    description: The internal port used by the application
    required: false
    default: ''
  container_size:
    description: The size of the container. CPU/Memory. small|medium|large|xlarge
    required: false
    default: ''
  container_command:
    description: The command to be passed to the docker container. I.e. "['curl']"
    required: false
    default: ''
  container_args:
    description: The args to be passed to the docker container. I.e. "['-I', 'https://www.google.com']"
    required: false
    default: ''
  replicas:
    description: Define how many replicas you need
    required: false
    default: '1'
  secretsmanager:
    description: Enable secrets manager. To fetch secrets you have to provide the cluster name.
    required: false
    default: 'false'
  cluster_name:
    description: The cluster name. This is used by external secrets to fetch secrets from AWS based on this key "cluster/<cluster_name>/<app_name>"
    required: false
    default: ''
  fargate:
    description: If fargate should be enabled. This input will be removed when we have migrated to node groups.
    required: false
    default: 'true'
  schedule:
    description: A cronjob schedule. I.e. "0 * * * *"
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
