apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
spec:
  backendType: secretsManager
  dataFrom:
    - cluster/bogus-cluster/prevent-demo
metadata:
  labels:
    app: prevent-demo
    app.kubernetes.io/name: prevent-demo
  name: prevent-demo
  namespace: development
---
apiVersion: v1
kind: Secret
immutable: false
metadata:
  labels:
    app: prevent-demo
    app.kubernetes.io/name: prevent-demo
  name: prevent-demo
  namespace: development
stringData: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prevent-demo
    app.kubernetes.io/name: prevent-demo
    cdk8s.io/metadata.addr: prevent-demo-webservice-deployment-c828a493
  name: prevent-demo
  namespace: development
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: prevent-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prevent-demo
        app.kubernetes.io/name: prevent-demo
        cdk8s.io/metadata.addr: prevent-demo-webservice-deployment-c828a493
      name: prevent-demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: instance
                    operator: In
                    values:
                      - previews
      automountServiceAccountToken: true
      containers:
        - args:
            - -I
            - https://www.dignio.com
          command:
            - curl
          envFrom:
            - secretRef:
                name: prevent-demo
          image: 1337.dkr.ecr.eu-north-1.amazonaws.com/prevent-demo:1337
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 15
            tcpSocket:
              port: 5000
            timeoutSeconds: 60
          name: prevent-demo
          ports:
            - containerPort: 5000
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 15
            tcpSocket:
              port: 5000
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 1000m
              memory: 1536Mi
            requests:
              cpu: 1000m
              memory: 1536Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            runAsGroup: 3000
            runAsNonRoot: true
            runAsUser: 1000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 2000
        fsGroupChangePolicy: Always
        runAsNonRoot: true
      setHostnameAsFQDN: false
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: prevent-demo
    app.kubernetes.io/name: prevent-demo
    cdk8s.io/metadata.addr: prevent-demo-webservice-deployment-c828a493
  name: prevent-demo
  namespace: development
spec:
  externalIPs: []
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: prevent-demo
  type: NodePort
