apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: prevent-ui
  name: prevent-ui
  namespace: development
spec:
  externalIPs: []
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: prevent-ui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prevent-ui
  name: prevent-ui
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prevent-ui
  template:
    metadata:
      labels:
        app: prevent-ui
    spec:
      containers:
        - env: []
          image: 1337.dkr.ecr.eu-north-1.amazonaws.com/prevent-ui:9628f958eb4a69571cfee558624fa0a33fa49c4f
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            timeoutSeconds: 60
          name: prevent-ui
          ports:
            - containerPort: 80
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 80
            periodSeconds: 15
            timeoutSeconds: 60
          volumeMounts: []
      restartPolicy: Always
      volumes: []
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "20"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: ingress-prevent-ui
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/success-codes: "200"
    kubernetes.io/ingress.class: alb
  labels:
    app: prevent-ui
  name: prevent-ui
  namespace: development
spec:
  rules:
    - host: prevent.dev.dignio.dev
      http:
        paths:
          - backend:
              service:
                name: prevent-ui
                port:
                  number: 80
            path: /
            pathType: Prefix
