apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: prevent-api
  name: prevent-api
  namespace: development
spec:
  externalIPs: []
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    cdk8s.io/metadata.addr: prevent-api-develop-prevent-api-prevent-api-deployment-c877198f
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prevent-api
  name: prevent-api
  namespace: development
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      cdk8s.io/metadata.addr: prevent-api-develop-prevent-api-prevent-api-deployment-c877198f
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prevent-api
        cdk8s.io/metadata.addr: prevent-api-develop-prevent-api-prevent-api-deployment-c877198f
    spec:
      automountServiceAccountToken: true
      containers:
        - image: 1337.dkr.ecr.eu-north-1.amazonaws.com/prevent-api:9628f958eb4a69571cfee558624fa0a33fa49c4f
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /apii
              port: 5000
            periodSeconds: 15
            timeoutSeconds: 60
          name: prevent-api
          ports:
            - containerPort: 5000
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /apii
              port: 5000
            periodSeconds: 15
            timeoutSeconds: 60
          resources:
            limits:
              cpu: 1000m
              memory: 1536Mi
            requests:
              cpu: 1000m
              memory: 1536Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
spec:
  backendType: secretsManager
  dataFrom:
    - cluster/dev-k8s/prevent-api
metadata:
  labels:
    app: prevent-api
  name: prevent-api
  namespace: development
