apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
spec:
  backendType: secretsManager
  dataFrom:
    - cluster/bogus-cluster/prevent-demo
metadata:
  labels:
    app: prevent-demo
    app.kubernetes.io/name: prevent-demo
  name: prevent-demo
  namespace: development
---
apiVersion: v1
kind: Secret
immutable: false
metadata:
  labels:
    app: prevent-demo
    app.kubernetes.io/name: prevent-demo
  name: prevent-demo
  namespace: development
stringData: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prevent-demo
    app.kubernetes.io/name: prevent-demo
    cdk8s.io/metadata.addr: prevent-demo-worker-deployment-c8425636
  name: prevent-demo
  namespace: development
spec:
  minReadySeconds: 0
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: prevent-demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prevent-demo
        app.kubernetes.io/name: prevent-demo
        cdk8s.io/metadata.addr: prevent-demo-worker-deployment-c8425636
      name: prevent-demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: instance
                    operator: In
                    values:
                      - ng-development
      automountServiceAccountToken: true
      containers:
        - args:
            - -I
            - https://www.dignio.com
          command:
            - curl
          envFrom:
            - secretRef:
                name: prevent-demo
          image: 1337.dkr.ecr.eu-north-1.amazonaws.com/prevent-demo:1337
          imagePullPolicy: Always
          name: prevent-demo
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroupChangePolicy: Always
        runAsNonRoot: false
      setHostnameAsFQDN: false
