// generated by cdk8s
import { ApiObject } from 'cdk8s';
/**
 * CronJob represents the configuration of a single cron job.
 */
export default class CronJob extends ApiObject {
    constructor(scope, ns, options) {
        super(
            scope,
            ns,
            Object.assign(Object.assign({}, options), {
                kind: 'CronJob',
                apiVersion: 'batch/v1',
            })
        );
    }
}
