name: Test action
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  test-generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # === Test against the repo's copy of the action
      - uses: ./
        name: Generate the Kubernetes manifest
        id: generate_manifest
        with:
          # These must be specified for the action to work
          app_name: prevent-demo
          service_type: webservice
          namespace: development
          docker_image: 1337.dkr.ecr.eu-north-1.amazonaws.com/prevent-demo:1337

          # Add secret config
          secretsmanager: true
          cluster_name: bogus-cluster

          # These are optional
          replicas: 1
          port: 5000
          container_port: 5000
          container_size: medium
          container_command: '["curl"]'
          container_args: '["-I", "https://www.dignio.com"]'

      # === Echo the output to see if it actually works
      - name: Echo the manifest output
        run: "echo ${{steps.generate_manifest.outputs.manifest}} | base64 --decode >> /tmp/k8s.manifest.yaml"

      # === Compare the files
      - name: Compare the output with the fixture
        run: "cmp $GITHUB_WORKSPACE/fixture/prevent-api.yaml /tmp/k8s.manifest.yaml || exit 1"

